services:
  app-dev:
    container_name: app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/usr/src/app/src/
      - ./public:/usr/src/app/public/
    environment:
      - CHOKIDAR_USEPOLLING=true
